.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH replay 1  "replay " 
.SH NAME
replay \- Replay execution from a previously exported trace file
.SH SYNOPSIS
\fBreplay\fR [\fB\-c\fR|\fB\-\-contract\fR] [\fB\-\-replay\-until\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fITRACE_FILE\fR> 
.SH DESCRIPTION
Replay execution from a previously exported trace file
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-contract\fR \fI<CONTRACT>\fR
Path to the contract WASM file (optional, defaults to trace file\*(Aqs contract path)
.TP
\fB\-\-replay\-until\fR \fI<REPLAY_UNTIL>\fR
Stop replay at step N (0\-based index into call sequence)
.TP
\fB\-o\fR, \fB\-\-output\fR \fI<OUTPUT>\fR
Output file for the diff report (default: stdout)
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Show verbose output during replay
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITRACE_FILE\fR>
Path to the trace JSON file to replay
