.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH inspect 1  "inspect " 
.SH NAME
inspect \- Inspect contract information without executing
.SH SYNOPSIS
\fBinspect\fR <\fB\-c\fR|\fB\-\-contract\fR> [\fB\-\-functions\fR] [\fB\-\-metadata\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Inspect contract information without executing
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-contract\fR \fI<CONTRACT>\fR
Path to the contract WASM file
.TP
\fB\-\-functions\fR
Show exported functions
.TP
\fB\-\-metadata\fR
Show contract metadata
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
