.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH upgrade-check 1  "upgrade-check " 
.SH NAME
upgrade\-check \- Check compatibility between two contract versions
.SH SYNOPSIS
\fBupgrade\-check\fR <\fB\-\-old\fR> <\fB\-\-new\fR> [\fB\-\-output\fR] [\fB\-\-output\-file\fR] [\fB\-\-test\-inputs\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check compatibility between two contract versions
.SH OPTIONS
.TP
\fB\-\-old\fR \fI<OLD>\fR
Path to the old (current) contract WASM file
.TP
\fB\-\-new\fR \fI<NEW>\fR
Path to the new (upgraded) contract WASM file
.TP
\fB\-\-output\fR \fI<OUTPUT>\fR [default: text]
Output format: text (default) or json
.TP
\fB\-\-output\-file\fR \fI<OUTPUT_FILE>\fR
Write report to file instead of stdout
.TP
\fB\-\-test\-inputs\fR \fI<TEST_INPUTS>\fR
Test inputs as JSON object mapping function names to argument arrays e.g. \*(Aq{"vote": [1, true], "create_proposal": ["title", "desc"]}\*(Aq
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
